name: tradecorp
services:
  jupyter:
    # Image a jour pour PySpark Notebook
    build: .
    container_name: tradecorp_spark
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - "./notebooks:/home/jovyan/work"
      - "./data:/home/jovyan/data"
      - "./src:/home/jovyan/src"
      - "./tests:/home/jovyan/tests"
      - "./.env:/home/jovyan/.env"
      - "./log4j2.properties:/usr/local/spark/conf/log4j2.properties"
    environment:
      PYSPARK_SUBMIT_ARGS: "--packages org.apache.hadoop:hadoop-azure:3.3.4,org.postgresql:postgresql:42.7.0"
  postgres:
    image: postgres:16
    container_name: tradecorp_postgres
    environment:
      POSTGRES_USER: tradecorp
      POSTGRES_PASSWORD: tradecorp
      POSTGRES_DB: tradecorp
    ports:
      - "5434:5432"
    volumes:
     - "pgdata:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    container_name: tradecorp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tradecorp.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes: 
      - "pgadmin_data:/var/lib/pgadmin"

volumes:
  pgadmin_data:
    name: tradecorp_pgadmin_data
  pgdata:
    name: tradecorp_pgdata